import { beforeAll, beforeEach, describe, expect, it, jest } from "@jest/globals";
import { registrations, programPackages } from "@/db/schema";
import { databaseHarness, NOW, FUTURE, sqlQuery } from "./database-harness";
import { program } from "./registration-fixtures";
const h = databaseHarness(); const verify = jest.fn<typeof import("@/lib/verify-renewal-verification-token").verifyRenewalVerificationToken>(); const sync = jest.fn<() => Promise<void>>();
let options: typeof import("@/lib/renewal-options").getRenewalOptions;
const history = { trainingGroupId: 1, trainingGroupSlug: "development", trainingGroupName: "Development", minimumAge: 9, maximumAge: 12, capacity: 2, dateOfBirth: "2015-06-15" };
beforeAll(async () => { jest.doMock("@/db", () => ({ db: h.db })); jest.doMock("@/lib/verify-renewal-verification-token", () => ({ verifyRenewalVerificationToken: verify })); jest.doMock("@/lib/synchronize-registration-statuses", () => ({ synchronizeRegistrationStatuses: sync })); ({ getRenewalOptions: options } = await import("@/lib/renewal-options")); });
beforeEach(() => { h.reset(); verify.mockResolvedValue({ status: "valid", playerId: 4, playerName: "Test Player", expiresAt: FUTURE }); sync.mockResolvedValue(); });
function initial(paidThrough = "2026-09-30") { h.read(registrations); h.read(registrations); h.read(registrations, history); h.read(registrations, { endsOn: paidThrough }); h.read(programPackages, { ...program, displayName: "Three months", slug: "three-months" }); }
describe("renewal options", () => {
  it("rejects invalid verification before further queries", async () => { verify.mockResolvedValue({ status: "invalid" }); expect(await options("bad", NOW)).toEqual({ status: "invalid-token" }); expect(h.db.select).not.toHaveBeenCalled(); });
  it.each([[0, { reservationExpiresAt: FUTURE }, "payment-pending"], [1, { endsOn: "2026-12-31" }, "upcoming-registration"]] as const)("blocks pending or future registration", async (index, row, reason) => { initial(); h.reads[index].rows = [row]; expect(await options("synthetic-token", NOW)).toMatchObject({ status: "blocked", reason }); expect(h.writes()).toEqual([]); });
  it.each([[2, "registration-history-unavailable"], [4, "packages-unavailable"]] as const)("blocks absent history/packages", async (index, reason) => { initial(); h.reads[index].rows = []; expect(await options("synthetic-token", NOW)).toMatchObject({ status: "blocked", reason }); });
  it.each([["2026-08-31", "2026-10-01"], ["2026-11-15", "2026-11-16"]])("uses paid-through %s for renewal start", async (paidThrough, renewsOn) => { initial(paidThrough); h.read(registrations, { occupiedSpots: 1 }); expect(await options("synthetic-token", NOW)).toMatchObject({ status: "ready", renewsOn, trainingGroup: { id: 1 }, programPackages: [expect.objectContaining({ id: 2 })] }); expect(h.writes()).toEqual([]); });
  it("does not advertise packages to a player who has aged out", async () => { initial(); h.reads[2].rows = [{ ...history, dateOfBirth: "2013-01-01" }]; expect(await options("synthetic-token", NOW)).toMatchObject({ status: "blocked", reason: "packages-unavailable" }); });
  it("offers only packages with capacity throughout their own period", async () => { initial(); h.reads[4].rows = [{ ...program, id: 2, durationMonths: 1 }, { ...program, id: 3, durationMonths: 3 }]; h.read(registrations, { occupiedSpots: 1 }); h.read(registrations, { occupiedSpots: 2 }); const result = await options("synthetic-token", NOW); expect(result).toMatchObject({ status: "ready", programPackages: [expect.objectContaining({ id: 2 })] }); if (result.status === "ready") expect(result.programPackages).toHaveLength(1); });
  it("requires paid history consistent with the final transaction", async () => { initial(); h.read(registrations, { occupiedSpots: 0 }); await options("synthetic-token", NOW); const query = sqlQuery(h.queries(registrations)[2]); expect(query.params).toContain("succeeded"); expect(query.params).not.toContain("pending_payment"); expect(sync.mock.invocationCallOrder[0]).toBeLessThan(h.db.select.mock.invocationCallOrder[0]); });
  it("rejects malformed stored dates", async () => { initial("2026-02-30"); await expect(options("synthetic-token", NOW)).rejects.toThrow("stored registration date"); });
  it("propagates database errors", async () => { initial(); h.reads[0].error = new Error("Synthetic query failure"); await expect(options("synthetic-token", NOW)).rejects.toThrow("Synthetic query failure"); });
});
