import { afterEach, beforeAll, beforeEach, describe, expect, it, jest } from "@jest/globals";
const construct = jest.fn<(...args: unknown[]) => unknown>(); const processEvent = jest.fn<(...args: unknown[]) => Promise<unknown>>();
let post: typeof import("@/app/api/stripe/webhook/route").POST;
beforeAll(async () => { jest.doMock("@/lib/stripe", () => ({ getStripeClient: () => ({ webhooks: { constructEvent: construct } }) })); jest.doMock("@/lib/process-stripe-webhook-event", () => ({ processStripeWebhookEvent: processEvent })); ({ POST: post } = await import("@/app/api/stripe/webhook/route")); });
beforeEach(() => { jest.clearAllMocks(); construct.mockReset().mockReturnValue({ id: "evt_fixture" }); processEvent.mockReset().mockResolvedValue({}); jest.replaceProperty(process, "env", { ...process.env, STRIPE_WEBHOOK_SECRET: "whsec_synthetic" }); jest.spyOn(console, "error").mockImplementation(() => {}); });
afterEach(() => { jest.restoreAllMocks(); });
function request(signature: string | null = "t=123,v1=synthetic", body = "synthetic-private-payload", headers: Record<string, string> = {}) { return new Request("https://academy.example/api/stripe/webhook", { method: "POST", headers: { ...(signature === null ? {} : { "stripe-signature": signature }), ...headers }, body }); }
describe("Stripe webhook HTTP boundary", () => {
  it.each([null, "", "bad", "t=123", "v1=abc", "t=1,v1=" + "a".repeat(4096)])("rejects missing or malformed signature", async signature => { const response = await post(request(signature)); expect(response.status).toBe(400); expect(response.headers.get("cache-control")).toBe("no-store"); expect(construct).not.toHaveBeenCalled(); expect(processEvent).not.toHaveBeenCalled(); });
  it.each([undefined, "", "invalid", "whsec_has space"])("fails closed for invalid webhook configuration", async secret => { if (secret === undefined) delete process.env.STRIPE_WEBHOOK_SECRET; else process.env.STRIPE_WEBHOOK_SECRET = secret; const response = await post(request()); expect(response.status).toBe(500); expect(construct).not.toHaveBeenCalled(); expect(JSON.stringify(jest.mocked(console.error).mock.calls)).not.toContain("whsec_synthetic"); });
  it("passes the unchanged raw bytes to signature verification before processing", async () => { const response = await post(request()); expect(response.status).toBe(200); expect(await response.json()).toEqual({ received: true }); expect(construct).toHaveBeenCalledWith(Buffer.from("synthetic-private-payload"), "t=123,v1=synthetic", "whsec_synthetic"); expect(processEvent).toHaveBeenCalledWith({ id: "evt_fixture" }); expect(construct.mock.invocationCallOrder[0]).toBeLessThan(processEvent.mock.invocationCallOrder[0]); });
  it.each([true, false])("rejects oversized body with declared size = %p", async declared => { const response = await post(request(undefined, "x".repeat(1048577), declared ? { "content-length": "1048577" } : {})); expect(response.status).toBe(413); expect(construct).not.toHaveBeenCalled(); expect(processEvent).not.toHaveBeenCalled(); });
  it.each(["signature", "processing"])("returns safe %s failure and sanitized logs", async stage => { const failure = new Error("synthetic-private-payload whsec_synthetic guardian@example.com"); if (stage === "signature") construct.mockImplementation(() => { throw failure; }); else processEvent.mockRejectedValue(failure); const response = await post(request()); expect(response.status).toBe(stage === "signature" ? 400 : 500); const output = JSON.stringify([await response.json(), jest.mocked(console.error).mock.calls]); expect(output).not.toContain("synthetic-private-payload"); expect(output).not.toContain("guardian@example.com"); expect(output).not.toContain("whsec_synthetic"); if (stage === "signature") expect(processEvent).not.toHaveBeenCalled(); });
});
